<h3 style ="text-decoration:underline"><center>Les tableaux Numpy<center></h3>

<h3 style ="text-decoration: underline"> Créer un ndarray</h3>

<h3 style="text-decoration:underline">Créer un ndarray à partir de listes</h3>

In [1]:
import numpy as np 

In [3]:
notre_tableau = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(notre_tableau)
type(notre_tableau)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


numpy.ndarray

In [5]:
mon_array_bidim = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mon_array_bidim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Pour sélectionner la valeur de la troisième colonne première ligne
print(mon_array_bidim[0][2])
print(mon_array_bidim[0,2])

# Pour sélectionner la première ligne
print(mon_array_bidim[:,0])

# Pour sélectionner la première colonne 
print(mon_array_bidim[0,:])

3
3
[1 4 7]
[1 2 3]


### Il s'agit d'un tableau d'entiers ici, et on ne pourrait pas changer une valeur par un type caractère par exemple, cela génèrerait une erreur. 

In [7]:
mon_array_bidim[0,0] = "texte"

ValueError: invalid literal for int() with base 10: 'texte'

In [10]:
mon_array_bidim[0,0] = 0.5
print(mon_array_bidim)

[[0 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
mon_array_bidim[0,0] = 10
print(mon_array_bidim)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [13]:
mon_array_bidim.dtype   # int 64 for float int32 for integer

dtype('int64')

In [14]:
mon_array_bidim = np.array([[1.5, 2,3],[4,5.2,6],[7,8,9.1]], dtype =float)
print(mon_array_bidim)
mon_array_bidim.dtype

[[1.5 2.  3. ]
 [4.  5.2 6. ]
 [7.  8.  9.1]]


dtype('float64')

<h3 style ="text-decoration: underline">1.1.2 Créer un ndarray grâce à des fonctions numpy</h3>

In [16]:
# np.zeros() permet de créer un ndarray dont l'ensemble des éléments correspondent à la valeur zéro.
mon_array_zeros = np.zeros((4,6))
print(mon_array_zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [17]:
# Si on veut, on peut spéficier que le tableau est de type int et non float
mon_array_zeros = np.zeros((4,6), dtype = int)
print(mon_array_zeros)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [18]:
mon_array_ones = np.ones((4,6), dtype = int)
print(mon_array_ones)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [19]:
# np.random.random() permet de créer un ndarray dont les valeurs des éléments sont aléatoires
mon_array_random = np.random.random((4,2))
print(mon_array_random)

[[0.69603239 0.13139639]
 [0.88015611 0.69968534]
 [0.06876784 0.01324471]
 [0.62641248 0.30278958]]


<h3 style="text-decoration:underline">1.1.3 Créer un ndarray à partir d'un fichier</h3>

Le fichier iris.csv contient des informations sur la longueur et la largeur des pétales et des sépales de 150 iris, sous forme de nombre réels, float. 
Les longueurs et les larguers de pétales et sépales permettent de différencier trois espèces d'Iris, représentées dans la 5ème colonne par des réels plutôt que le nom de l'espèse, étant donné que les ndarrays n'acceptent pas des type de données différents. 
L'espèce 1.0 correspond à l'espèce Setosa
L'espèce 2.0 correspond à l'espèse Versicolor 
L'espèse 3.0 correspond à l'espèce Virginica

In [24]:
import numpy as np 
# Il faut que le fichier jupyter soit ua même endroit que le fichier a lire, ou spécifier le dosser dans lequel il est.
# %pwd to get the current path
iris = np.genfromtxt("iris.csv", delimiter=";", skip_header=True, encoding = "latin-1")
print(iris)
print(iris.dtype)
type(iris)

[[5.1 3.5 1.4 0.2 1. ]
 [4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [4.6 3.4 1.4 0.3 1. ]
 [5.  3.4 1.5 0.2 1. ]
 [4.4 2.9 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [4.8 3.4 1.6 0.2 1. ]
 [4.8 3.  1.4 0.1 1. ]
 [4.3 3.  1.1 0.1 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [4.6 3.6 1.  0.2 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [4.8 3.4 1.9 0.2 1. ]
 [5.  3.  1.6 0.2 1. ]
 [5.  3.4 1.6 0.4 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.4 1.4 0.2 1. ]
 [4.7 3.2 1.6 0.2 1. ]
 [4.8 3.1 1.6 0.2 1. ]
 [5.4 3.4 1.5 0.4 1. ]
 [5.2 4.1 1.5 0.1 1. ]
 [5.5 4.2 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.2 1. ]
 [5.  3.2 1.2 0.2 1. ]
 [5.5 3.5 1.3 0.2 1. ]
 [4.9 3.6 1.4 0.1 1. ]
 [4.4 3.  1.3 0.2 1. ]
 [5.1 3.4 1.5 0.2 1. ]
 [5.  3.5 1.3 0.3 1. ]
 [4.5 2.3 1.3 0.3 1. ]
 [4.4 3.2 1.3 0.2 1. ]
 [5.  3.5 1

numpy.ndarray

In [25]:
np.savetxt("iris_2.csv", iris, delimiter=";")

<h3 style ="text-decoration:underline"> 1.2. Indexation</h3>

<h3 style="text-decoration:underline">1.2.1. Indexation simple :</h3>

In [26]:
iris[2,1]

3.2

<h3>Modifions la valeur à la 3ème ligne 2ème colonne</h3>

In [28]:
iris[2,1] = 4
iris[2,1]

4.0

In [30]:
iris[2,1] = 3.2
iris[2,1]

3.2

<h3 style ="text-decoration: underline">1.2.2 Indexation booléenne</h3>

Pour sélectionner une portion du tableau on peut utiliser des masques booléens.

Rappels les opérateurs relationnels, permettent de comparer des valeurs: ==, !=; <, >, <=, >=. 
Si on ne souhaite garder que les vlaeurs supérieurs à 2 dans ce tableau, peu importe la colonne:

In [32]:
iris[iris>2]

array([5.1, 3.5, 4.9, 3. , 4.7, 3.2, 4.6, 3.1, 5. , 3.6, 5.4, 3.9, 4.6,
       3.4, 5. , 3.4, 4.4, 2.9, 4.9, 3.1, 5.4, 3.7, 4.8, 3.4, 4.8, 3. ,
       4.3, 3. , 5.8, 4. , 5.7, 4.4, 5.4, 3.9, 5.1, 3.5, 5.7, 3.8, 5.1,
       3.8, 5.4, 3.4, 5.1, 3.7, 4.6, 3.6, 5.1, 3.3, 4.8, 3.4, 5. , 3. ,
       5. , 3.4, 5.2, 3.5, 5.2, 3.4, 4.7, 3.2, 4.8, 3.1, 5.4, 3.4, 5.2,
       4.1, 5.5, 4.2, 4.9, 3.1, 5. , 3.2, 5.5, 3.5, 4.9, 3.6, 4.4, 3. ,
       5.1, 3.4, 5. , 3.5, 4.5, 2.3, 4.4, 3.2, 5. , 3.5, 5.1, 3.8, 4.8,
       3. , 5.1, 3.8, 4.6, 3.2, 5.3, 3.7, 5. , 3.3, 7. , 3.2, 4.7, 6.4,
       3.2, 4.5, 6.9, 3.1, 4.9, 5.5, 2.3, 4. , 6.5, 2.8, 4.6, 5.7, 2.8,
       4.5, 6.3, 3.3, 4.7, 4.9, 2.4, 3.3, 6.6, 2.9, 4.6, 5.2, 2.7, 3.9,
       5. , 3.5, 5.9, 3. , 4.2, 6. , 2.2, 4. , 6.1, 2.9, 4.7, 5.6, 2.9,
       3.6, 6.7, 3.1, 4.4, 5.6, 3. , 4.5, 5.8, 2.7, 4.1, 6.2, 2.2, 4.5,
       5.6, 2.5, 3.9, 5.9, 3.2, 4.8, 6.1, 2.8, 4. , 6.3, 2.5, 4.9, 6.1,
       2.8, 4.7, 6.4, 2.9, 4.3, 6.6, 3. , 4.4, 6.8, 2.8, 4.8, 6.

In [33]:
 #Tableau unidimensionnel donne donc une seule valeur.
iris[iris>2].shape

(472,)

In [35]:
# On peut choisir le nombre d'élement d'une colonne particulière
iris[iris>2].shape[0]

472

L'expression booléenne qui génère un nouveau tableau, de même dimension que le tableau iris, mais qui contient uniquement des booléens, True ou False

In [36]:
iris > 2

array([[ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, Fal

Pour appliquer la condition sur une colonne particulière du tableau, il faut sélectionner en écrivant le maque booléen de la manière suivante: 

In [39]:
# Conserve uniquement les valeurs correspondant à l'iris de cat 3.
#iris[iris[:,4]==3]
iris = iris[iris[:,0]>5]

Ici nous venons de sélectionner uniquement les valeurs où la longueur des sépales est supérieur à 5cm, cad où les valeurs de la 1ere colonne sont supérieur à 5. 

Dans la cellule qui suit on isole la partie "iris[;,0]>5". C'est cette partie qui génère un ndarray à 1 dimension contenant 150 valeurs (car il y a 150 lignes dans le tableau). 
Ansi, Python sait qu'il doit garder uniquement les lignes à l'indece où la valeur est à True dans "iris[:,0]>5".

In [41]:
iris[:,0]>5

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

<h3 style="text-decoration: underline">1.2.3 Fancy indexing (littéralement indexation fantaisie...)<h3>

Le but est simple: donner un tableau d'indice(ou une liste d'indices) entre crochets à notre ndarray pour sélectionner plusieurs éléments non consécutifs. 


In [46]:
notre_tableau = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print("Contenu du notre_tableau : ")
print(notre_tableau)
print("Nouveau tableau après fancy indexing : ")
indices = np.array([[4,10,5],[12,8,9]])
print(notre_tableau[indices])

Contenu du notre_tableau : 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Nouveau tableau après fancy indexing : 
[[ 5 11  6]
 [13  9 10]]


In [48]:
A = notre_tableau[indices]
print(A[0,2])

6


<h3 style="text-decoration:underline">1.3 Accéder aux éléments par tranche (slicing)<h3>

<h3 style ="text-decoration: underline">1.3.1 Slicing sur un tableau Numpy à 1 dimension</h3>

In [50]:
# Les trois premiers éléments
notre_tableau[:3]

array([1, 2, 3])

In [51]:
# Les derniers éléments à partir de l'index 10
notre_tableau[10:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [52]:
# Du 3ème au 7ème éléments
notre_tableau[3:7]

array([4, 5, 6, 7])

In [53]:
# Tous les éléments avec un pas de 2
notre_tableau[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [54]:
# Tous les élements entre 3 et 8 avec un pas de 3
notre_tableau[3:8:3]

array([4, 7])

<h3 style ="text-decoration: underline">1.3.2 Slicing sur un tableau NUmpy à 2 dimensions</h3>

In [56]:
# Ici on sélectionne les deux 1ères lignes des 4 1ères colonnes
iris[:2,:4]

array([[5.1, 3.5, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

In [73]:
# Les dernières lignes à partir de l'index 145 des dernières colonnes à partir de l'index 2
iris[145:,2:]

array([], shape=(0, 3), dtype=float64)

In [60]:
# Affiche toutes les colonnes de la ligne 0, la première ligne 
iris[0,:]

array([5.1, 3.5, 1.4, 0.2, 1. ])

In [62]:
iris[:,0]

array([5.1, 5.4, 5.4, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 5.1, 5.2,
       5.2, 5.4, 5.2, 5.5, 5.5, 5.1, 5.1, 5.1, 5.3, 7. , 6.4, 6.9, 5.5,
       6.5, 5.7, 6.3, 6.6, 5.2, 5.9, 6. , 6.1, 5.6, 6.7, 5.6, 5.8, 6.2,
       5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7, 6. , 5.7, 5.5, 5.5,
       5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5, 6.1, 5.8, 5.6, 5.7,
       5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3, 6.5, 7.6, 7.3, 6.7, 7.2,
       6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5, 7.7, 7.7, 6. , 6.9, 5.6, 7.7,
       6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2, 7.4, 7.9, 6.4, 6.3, 6.1, 7.7,
       6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8, 6.8, 6.7, 6.7, 6.3, 6.5, 6.2,
       5.9])

In [64]:
# Affiche toute les colonnes de la dernière ligne. 
iris[-1,:]

array([5.9, 3. , 5.1, 1.8, 3. ])

<h3 style="text-decoration:underline">1.4 Notion de vue et copie<h3>

In [66]:
sous_tableau = notre_tableau[:5]
sous_tableau

array([1, 2, 3, 4, 5])

In [67]:
sous_tableau[0] = 10
sous_tableau 

array([10,  2,  3,  4,  5])

In [68]:
notre_tableau 

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

La première valeur est devenue 10 aussi alors que nous avons modifié l'objet sous_tableau et non pas notre tableau ! 
Lorsqu'on fait du slicing sur un tableau, ce qu'il retourne, c'est une vue du tableau et non pas une copie du tableau. Ce n'est pas un nouveal ndarray. 

In [71]:
sous_tableau = notre_tableau[:5].copy()
print(sous_tableau)

[10  2  3  4  5]


In [72]:
sous_tableau[0] = 1
print(sous_tableau)
print(notre_tableau)

[1 2 3 4 5]
[10  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


<h3 style ="text-decoration: underline">2. Les opérations mathématique avec Numpy</h3>

<h3 style ="text-decoration: underline">2.1 Les opérations arithmétiques</h3>
centré réduire = soustraire moyenne et divisé par variance. 

In [75]:
mon_tableau = np.array([[10,11,12],[13,14,15],[16,17,18]])
mon_tableau

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [76]:
np.add(mon_tableau, 10)

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [81]:
A = np.multiply(mon_tableau,20)
print(A)
print(mon_tableau)

[[200 220 240]
 [260 280 300]
 [320 340 360]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [82]:
mon_tableau2 = np.array([10,20,30])
mon_tableau2

array([10, 20, 30])

In [84]:
np.subtract(mon_tableau,mon_tableau2)

array([[  0,  -9, -18],
       [  3,  -6, -15],
       [  6,  -3, -12]])

In [85]:
# Produit matriciel
mon_tableau3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mon_tableau3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
np.multiply(mon_tableau,mon_tableau3)

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

<h3 style ="text-decoration: underline">2.2 Les fonctions d'agrégations</h3>

In [88]:
import numpy as np 
print("Somme sur l'ensemble des éléments: ")
print(np.sum(iris))

# axis = 0 signifie qu'on veut effectuer le calcule par colonne
# et axis = 1 signifie qu'on veut effectuer le calcul par ligne. 
print("Somme par colonne:")
print(np.sum(iris, axis =0))
print("Somme par ligne: ")
print(np.sum(iris, axis =1))

Somme sur l'ensemble des éléments: 
2024.2
Somme par colonne:
[723.3 359.7 509.2 169.  263. ]
Somme par ligne: 
[11.2 12.4 11.8 12.2 13.  12.  11.3 12.5 11.7 11.7 11.7 11.6 11.4 11.2
 11.7 11.9 12.3 11.5 11.2 12.2 11.7 11.7 18.3 17.6 18.4 15.1 17.4 16.3
 17.9 17.4 15.2 16.6 15.2 17.1 15.4 17.6 16.6 15.6 16.4 15.1 17.7 16.2
 17.2 16.8 16.9 17.4 17.8 18.4 16.9 14.8 14.8 14.6 15.6 17.4 16.4 17.5
 18.  16.3 16.  15.3 15.7 17.1 15.6 15.8 16.1 16.1 16.7 13.7 15.9 21.1
 18.5 21.1 19.6 20.5 22.3 21.3 19.8 22.4 19.8 19.3 20.4 18.2 19.1 20.2
 19.8 23.4 22.5 17.7 21.1 18.3 22.2 18.7 20.8 21.2 18.6 18.8 19.9 20.6
 21.2 23.1 20.  18.7 18.7 22.1 20.7 19.8 18.6 20.5 20.8 20.4 18.5 21.2
 21.2 20.2 18.7 19.7 20.3 18.8]


In [89]:
print(np.mean(iris, axis=0))
print(np.std(iris, axis = 0))

[6.12966102 3.04830508 4.31525424 1.43220339 2.22881356]
[0.68498538 0.44354753 1.52213204 0.66865427 0.74117425]


In [90]:
print(np.max(iris,axis=0))

[7.9 4.4 6.9 2.5 3. ]


Application du masque avec un booléen pour faire des stats sur uniquement 1 type d'iris.Calcul en colonne d'où axis = 0 pour faire les moyennes bien adéquate.  

In [96]:
iris3 = iris[iris[:,4] == 3]
iris2 = iris[iris[:,4] == 2]
iris1 = iris[iris[:,4] == 1]
# print(iris3)
# pour plusieurs conditions : print(iris[(iris[:,4] == 3) & (iris[:, 3] > 2)])
print(np.mean(iris3, axis = 0))
print(np.mean(iris2, axis = 0))
print(np.mean(iris1, axis = 0))

[6.62244898 2.98367347 5.57346939 2.03265306 3.        ]
[5.99787234 2.80425532 4.31702128 1.34680851 2.        ]
[5.31363636 3.71363636 1.50909091 0.27727273 1.        ]


<h3 style ="text-decoration: underline">2. Inspecter un tableau grâce aux attributs de Numpy</h3>

In [98]:
print(iris.size)
print(iris.shape)
print(iris.ndim)
print(iris.dtype)

590
(118, 5)
2
float64


In [99]:
#Transposée c'est mettre ligne en colonne et colonne en ligne 
# calcul matriciel, jeu de données mauvais à transposer. 

<h3 style ="text-decoration: underline">4. Manipulation de tableaux Numpy</h3>
<h3 style ="text-decoration: underline">4.1 Ajouter et supprimer des éléments d'un tableau</h3>
<h3 style ="text-decoration: underline">4.1.1 AJouter des éléments dans un tableau</h3>

In [100]:
np.append(notre_tableau,[21,22,23,24,25])

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [102]:
np.append(iris,[[10,10,10,10,10]], axis = 0)

array([[ 5.1,  3.5,  1.4,  0.2,  1. ],
       [ 5.4,  3.9,  1.7,  0.4,  1. ],
       [ 5.4,  3.7,  1.5,  0.2,  1. ],
       [ 5.8,  4. ,  1.2,  0.2,  1. ],
       [ 5.7,  4.4,  1.5,  0.4,  1. ],
       [ 5.4,  3.9,  1.3,  0.4,  1. ],
       [ 5.1,  3.5,  1.4,  0.3,  1. ],
       [ 5.7,  3.8,  1.7,  0.3,  1. ],
       [ 5.1,  3.8,  1.5,  0.3,  1. ],
       [ 5.4,  3.4,  1.7,  0.2,  1. ],
       [ 5.1,  3.7,  1.5,  0.4,  1. ],
       [ 5.1,  3.3,  1.7,  0.5,  1. ],
       [ 5.2,  3.5,  1.5,  0.2,  1. ],
       [ 5.2,  3.4,  1.4,  0.2,  1. ],
       [ 5.4,  3.4,  1.5,  0.4,  1. ],
       [ 5.2,  4.1,  1.5,  0.1,  1. ],
       [ 5.5,  4.2,  1.4,  0.2,  1. ],
       [ 5.5,  3.5,  1.3,  0.2,  1. ],
       [ 5.1,  3.4,  1.5,  0.2,  1. ],
       [ 5.1,  3.8,  1.9,  0.4,  1. ],
       [ 5.1,  3.8,  1.6,  0.2,  1. ],
       [ 5.3,  3.7,  1.5,  0.2,  1. ],
       [ 7. ,  3.2,  4.7,  1.4,  2. ],
       [ 6.4,  3.2,  4.5,  1.5,  2. ],
       [ 6.9,  3.1,  4.9,  1.5,  2. ],
       [ 5.5,  2.3,  4. ,

In [103]:
# L'élément 42 a été ajouté à l'index 1, 
# Donc à la place de la valeur 2, et la valeur 2 se retrouve alors à l'index2.
np.insert(notre_tableau, 1, 42)

array([10, 42,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [104]:
np.insert(notre_tableau, 1, [42, 43, 44, 45, 46])

array([10, 42, 43, 44, 45, 46,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15, 16, 17, 18, 19, 20])

In [105]:
np.insert(iris, 1, [10,10,10,10,10], axis = 0)
# On vient d'insérer une ligne en 2ème position du tableau iris, contenant 5 valeurs

array([[ 5.1,  3.5,  1.4,  0.2,  1. ],
       [10. , 10. , 10. , 10. , 10. ],
       [ 5.4,  3.9,  1.7,  0.4,  1. ],
       [ 5.4,  3.7,  1.5,  0.2,  1. ],
       [ 5.8,  4. ,  1.2,  0.2,  1. ],
       [ 5.7,  4.4,  1.5,  0.4,  1. ],
       [ 5.4,  3.9,  1.3,  0.4,  1. ],
       [ 5.1,  3.5,  1.4,  0.3,  1. ],
       [ 5.7,  3.8,  1.7,  0.3,  1. ],
       [ 5.1,  3.8,  1.5,  0.3,  1. ],
       [ 5.4,  3.4,  1.7,  0.2,  1. ],
       [ 5.1,  3.7,  1.5,  0.4,  1. ],
       [ 5.1,  3.3,  1.7,  0.5,  1. ],
       [ 5.2,  3.5,  1.5,  0.2,  1. ],
       [ 5.2,  3.4,  1.4,  0.2,  1. ],
       [ 5.4,  3.4,  1.5,  0.4,  1. ],
       [ 5.2,  4.1,  1.5,  0.1,  1. ],
       [ 5.5,  4.2,  1.4,  0.2,  1. ],
       [ 5.5,  3.5,  1.3,  0.2,  1. ],
       [ 5.1,  3.4,  1.5,  0.2,  1. ],
       [ 5.1,  3.8,  1.9,  0.4,  1. ],
       [ 5.1,  3.8,  1.6,  0.2,  1. ],
       [ 5.3,  3.7,  1.5,  0.2,  1. ],
       [ 7. ,  3.2,  4.7,  1.4,  2. ],
       [ 6.4,  3.2,  4.5,  1.5,  2. ],
       [ 6.9,  3.1,  4.9,

In [106]:
np.insert(iris,1,[10,10,10,10,10])

array([ 5.1, 10. , 10. , 10. , 10. , 10. ,  3.5,  1.4,  0.2,  1. ,  5.4,
        3.9,  1.7,  0.4,  1. ,  5.4,  3.7,  1.5,  0.2,  1. ,  5.8,  4. ,
        1.2,  0.2,  1. ,  5.7,  4.4,  1.5,  0.4,  1. ,  5.4,  3.9,  1.3,
        0.4,  1. ,  5.1,  3.5,  1.4,  0.3,  1. ,  5.7,  3.8,  1.7,  0.3,
        1. ,  5.1,  3.8,  1.5,  0.3,  1. ,  5.4,  3.4,  1.7,  0.2,  1. ,
        5.1,  3.7,  1.5,  0.4,  1. ,  5.1,  3.3,  1.7,  0.5,  1. ,  5.2,
        3.5,  1.5,  0.2,  1. ,  5.2,  3.4,  1.4,  0.2,  1. ,  5.4,  3.4,
        1.5,  0.4,  1. ,  5.2,  4.1,  1.5,  0.1,  1. ,  5.5,  4.2,  1.4,
        0.2,  1. ,  5.5,  3.5,  1.3,  0.2,  1. ,  5.1,  3.4,  1.5,  0.2,
        1. ,  5.1,  3.8,  1.9,  0.4,  1. ,  5.1,  3.8,  1.6,  0.2,  1. ,
        5.3,  3.7,  1.5,  0.2,  1. ,  7. ,  3.2,  4.7,  1.4,  2. ,  6.4,
        3.2,  4.5,  1.5,  2. ,  6.9,  3.1,  4.9,  1.5,  2. ,  5.5,  2.3,
        4. ,  1.3,  2. ,  6.5,  2.8,  4.6,  1.5,  2. ,  5.7,  2.8,  4.5,
        1.3,  2. ,  6.3,  3.3,  4.7,  1.6,  2. ,  6

<h3 style ="text-decoration: underline">4.1.2 Supprimer des éléments d'un tableau</h3>

In [107]:
np.delete(iris,1,axis =1)
# On supprime la 2ème colonne (à l'index 1)

array([[5.1, 1.4, 0.2, 1. ],
       [5.4, 1.7, 0.4, 1. ],
       [5.4, 1.5, 0.2, 1. ],
       [5.8, 1.2, 0.2, 1. ],
       [5.7, 1.5, 0.4, 1. ],
       [5.4, 1.3, 0.4, 1. ],
       [5.1, 1.4, 0.3, 1. ],
       [5.7, 1.7, 0.3, 1. ],
       [5.1, 1.5, 0.3, 1. ],
       [5.4, 1.7, 0.2, 1. ],
       [5.1, 1.5, 0.4, 1. ],
       [5.1, 1.7, 0.5, 1. ],
       [5.2, 1.5, 0.2, 1. ],
       [5.2, 1.4, 0.2, 1. ],
       [5.4, 1.5, 0.4, 1. ],
       [5.2, 1.5, 0.1, 1. ],
       [5.5, 1.4, 0.2, 1. ],
       [5.5, 1.3, 0.2, 1. ],
       [5.1, 1.5, 0.2, 1. ],
       [5.1, 1.9, 0.4, 1. ],
       [5.1, 1.6, 0.2, 1. ],
       [5.3, 1.5, 0.2, 1. ],
       [7. , 4.7, 1.4, 2. ],
       [6.4, 4.5, 1.5, 2. ],
       [6.9, 4.9, 1.5, 2. ],
       [5.5, 4. , 1.3, 2. ],
       [6.5, 4.6, 1.5, 2. ],
       [5.7, 4.5, 1.3, 2. ],
       [6.3, 4.7, 1.6, 2. ],
       [6.6, 4.6, 1.3, 2. ],
       [5.2, 3.9, 1.4, 2. ],
       [5.9, 4.2, 1.5, 2. ],
       [6. , 4. , 1. , 2. ],
       [6.1, 4.7, 1.4, 2. ],
       [5.6, 3

In [108]:
np.delete(iris, [1,2,3,4], axis = 0)
# On supprime les lignes à l'index 1,2,3 et 4

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [5.4, 3.4, 1.5, 0.4, 1. ],
       [5.2, 4.1, 1.5, 0.1, 1. ],
       [5.5, 4.2, 1.4, 0.2, 1. ],
       [5.5, 3.5, 1.3, 0.2, 1. ],
       [5.1, 3.4, 1.5, 0.2, 1. ],
       [5.1, 3.8, 1.9, 0.4, 1. ],
       [5.1, 3.8, 1.6, 0.2, 1. ],
       [5.3, 3.7, 1.5, 0.2, 1. ],
       [7. , 3.2, 4.7, 1.4, 2. ],
       [6.4, 3.2, 4.5, 1.5, 2. ],
       [6.9, 3.1, 4.9, 1.5, 2. ],
       [5.5, 2.3, 4. , 1.3, 2. ],
       [6.5, 2.8, 4.6, 1.5, 2. ],
       [5.7, 2.8, 4.5, 1.3, 2. ],
       [6.3, 3.3, 4.7, 1.6, 2. ],
       [6.6, 2.9, 4.6, 1.3, 2. ],
       [5.2, 2.7, 3.9, 1.4, 2. ],
       [5.9, 3. , 4.2, 1.5, 2. ],
       [6. , 2.2, 4. , 1. , 2. ],
       [6.1, 2

In [109]:
np.delete(notre_tableau,1)

array([10,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

<h3 style ="text-decoration: underline">4.2 Diviser un tableau Numpy(split, hsplit et vsplit)</h3>

<h3 style ="text-decoration: underline">4.2.1 Sur un tableau à une dimension</h3>

In [110]:
notre_tableau

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [111]:
(notre_tableau1, notre_tableau2, notre_tableau3) = np.split(notre_tableau, [2,6])
print(notre_tableau1,notre_tableau2, notre_tableau3 )

[10  2] [3 4 5 6] [ 7  8  9 10 11 12 13 14 15 16 17 18 19 20]


<h3 style ="text-decoration: underline">4.2.2 Sur un tableau à 2 dimensions</h3>

In [113]:
array = np.array([[2,5,6],[9,10,11],[5,6,9]],dtype = "float")
print("Avant division")
print(array)
array1, array2 = np.vsplit(array, [2])
print("Après division")
print(array1)
print(array2)

Avant division
[[ 2.  5.  6.]
 [ 9. 10. 11.]
 [ 5.  6.  9.]]
Après division
[[ 2.  5.  6.]
 [ 9. 10. 11.]]
[[5. 6. 9.]]


In [115]:
array = np.array([[2,5,6],[9,10,11],[5,6,9]],dtype="float")
print("Avant division")
print(array)
array1,array2 = np.hsplit(array,[2])
print("Après division")
print(array1)
print(array2)

Avant division
[[ 2.  5.  6.]
 [ 9. 10. 11.]
 [ 5.  6.  9.]]
Après division
[[ 2.  5.]
 [ 9. 10.]
 [ 5.  6.]]
[[ 6.]
 [11.]
 [ 9.]]


<h3 style ="text-decoration: underline">4.3 Concaténer/combiner des tableaux</h3>

<h3 style ="text-decoration: underline">4.3.1 La fonction concatenate()<h3>

In [117]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9])
array3 = np.array([6,7,8,9])
print(array1)
print(array2)
np.concatenate([array1, array2, array3])

[1 2 3 4 5]
[6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9, 6, 7, 8, 9])

In [118]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype="float")
array2 = np.array([[2,5,6],[9,10,11],[5,6,9]],dtype="float")
print(array1)
print(array2)
np.concatenate([array1, array2])

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 2.  5.  6.]
 [ 9. 10. 11.]
 [ 5.  6.  9.]]


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 2.,  5.,  6.],
       [ 9., 10., 11.],
       [ 5.,  6.,  9.]])

In [119]:
array3 = np.array([[4,10,13],[7,14,15]], dtype = "float")
np.concatenate([array1, array2, array3])

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 2.,  5.,  6.],
       [ 9., 10., 11.],
       [ 5.,  6.,  9.],
       [ 4., 10., 13.],
       [ 7., 14., 15.]])

<h3 style ="text-decoration: underline">4.3.2 La fonction vstack() et hstack()</h3>

In [120]:
array1 = np.array([15,16,47])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype = "float")
print(array1)
print("----")
print(array2)
print("----")
print(np.vstack([array1, array2]))


array1 = np.array([[15],[16],[47]])
print("----")
print(array1)
print("----")
print(array2)
print("----")
print(np.hstack([array1,array2]))

[15 16 47]
----
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
----
[[15. 16. 47.]
 [ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
----
[[15]
 [16]
 [47]]
----
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
----
[[15.  1.  2.  3.]
 [16.  4.  5.  6.]
 [47.  7.  8.  9.]]


In [121]:
# multiplication de deux tableau ndarrays 
array2*array2

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]])

In [122]:
#produit matriciel entre les deux matrices array2
np.mat(array2)*np.mat(array2)

matrix([[ 30.,  36.,  42.],
        [ 66.,  81.,  96.],
        [102., 126., 150.]])

In [123]:
print(iris)

[[5.1 3.5 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.4 1.4 0.2 1. ]
 [5.4 3.4 1.5 0.4 1. ]
 [5.2 4.1 1.5 0.1 1. ]
 [5.5 4.2 1.4 0.2 1. ]
 [5.5 3.5 1.3 0.2 1. ]
 [5.1 3.4 1.5 0.2 1. ]
 [5.1 3.8 1.9 0.4 1. ]
 [5.1 3.8 1.6 0.2 1. ]
 [5.3 3.7 1.5 0.2 1. ]
 [7.  3.2 4.7 1.4 2. ]
 [6.4 3.2 4.5 1.5 2. ]
 [6.9 3.1 4.9 1.5 2. ]
 [5.5 2.3 4.  1.3 2. ]
 [6.5 2.8 4.6 1.5 2. ]
 [5.7 2.8 4.5 1.3 2. ]
 [6.3 3.3 4.7 1.6 2. ]
 [6.6 2.9 4.6 1.3 2. ]
 [5.2 2.7 3.9 1.4 2. ]
 [5.9 3.  4.2 1.5 2. ]
 [6.  2.2 4.  1.  2. ]
 [6.1 2.9 4.7 1.4 2. ]
 [5.6 2.9 3.6 1.3 2. ]
 [6.7 3.1 4.4 1.4 2. ]
 [5.6 3.  4.5 1.5 2. ]
 [5.8 2.7 4.1 1.  2. ]
 [6.2 2.2 4.5 1.5 2. ]
 [5.6 2.5 3.9 1.1 2. ]
 [5.9 3.2 4.8 1.8 2. ]
 [6.1 2.8 4.  1.3 2. ]
 [6.3 2.5 4.9 1.5 2. ]
 [6.1 2.8 4

In [130]:

mean_column = np.mean(iris[:,0:4], axis = 1)
print(mean_column)
new_iris = np.insert(iris, 5,mean_column, axis=1)
print(new_iris)


[2.55  2.85  2.7   2.8   3.    2.75  2.575 2.875 2.675 2.675 2.675 2.65
 2.6   2.55  2.675 2.725 2.825 2.625 2.55  2.8   2.675 2.675 4.075 3.9
 4.1   3.275 3.85  3.575 3.975 3.85  3.3   3.65  3.3   3.775 3.35  3.9
 3.65  3.4   3.6   3.275 3.925 3.55  3.8   3.7   3.725 3.85  3.95  4.1
 3.725 3.2   3.2   3.15  3.4   3.85  3.6   3.875 4.    3.575 3.5   3.325
 3.425 3.775 3.4   3.45  3.525 3.525 3.675 2.925 3.475 4.525 3.875 4.525
 4.15  4.375 4.825 4.575 4.2   4.85  4.2   4.075 4.35  3.8   4.025 4.3
 4.2   5.1   4.875 3.675 4.525 3.825 4.8   3.925 4.45  4.55  3.9   3.95
 4.225 4.4   4.55  5.025 4.25  3.925 3.925 4.775 4.425 4.2   3.9   4.375
 4.45  4.35  3.875 4.55  4.55  4.3   3.925 4.175 4.325 3.95 ]
[[5.1   3.5   1.4   0.2   1.    2.55 ]
 [5.4   3.9   1.7   0.4   1.    2.85 ]
 [5.4   3.7   1.5   0.2   1.    2.7  ]
 [5.8   4.    1.2   0.2   1.    2.8  ]
 [5.7   4.4   1.5   0.4   1.    3.   ]
 [5.4   3.9   1.3   0.4   1.    2.75 ]
 [5.1   3.5   1.4   0.3   1.    2.575]
 [5.7   3.8   1.7 

In [131]:
# Correction 
iris_mean = np.mean(iris[:,:4], axis=1)
iris_mean
print(np.insert(iris, 5,iris_mean, axis=1))

[[5.1   3.5   1.4   0.2   1.    2.55 ]
 [5.4   3.9   1.7   0.4   1.    2.85 ]
 [5.4   3.7   1.5   0.2   1.    2.7  ]
 [5.8   4.    1.2   0.2   1.    2.8  ]
 [5.7   4.4   1.5   0.4   1.    3.   ]
 [5.4   3.9   1.3   0.4   1.    2.75 ]
 [5.1   3.5   1.4   0.3   1.    2.575]
 [5.7   3.8   1.7   0.3   1.    2.875]
 [5.1   3.8   1.5   0.3   1.    2.675]
 [5.4   3.4   1.7   0.2   1.    2.675]
 [5.1   3.7   1.5   0.4   1.    2.675]
 [5.1   3.3   1.7   0.5   1.    2.65 ]
 [5.2   3.5   1.5   0.2   1.    2.6  ]
 [5.2   3.4   1.4   0.2   1.    2.55 ]
 [5.4   3.4   1.5   0.4   1.    2.675]
 [5.2   4.1   1.5   0.1   1.    2.725]
 [5.5   4.2   1.4   0.2   1.    2.825]
 [5.5   3.5   1.3   0.2   1.    2.625]
 [5.1   3.4   1.5   0.2   1.    2.55 ]
 [5.1   3.8   1.9   0.4   1.    2.8  ]
 [5.1   3.8   1.6   0.2   1.    2.675]
 [5.3   3.7   1.5   0.2   1.    2.675]
 [7.    3.2   4.7   1.4   2.    4.075]
 [6.4   3.2   4.5   1.5   2.    3.9  ]
 [6.9   3.1   4.9   1.5   2.    4.1  ]
 [5.5   2.3   4.    1.3  

In [146]:
row_mean = np.mean(iris, axis = 0)
print(row_mean)
print(np.insert(iris,iris.shape[0],row_mean,axis=0))

[6.12966102 3.04830508 4.31525424 1.43220339 2.22881356]
[[5.1        3.5        1.4        0.2        1.        ]
 [5.4        3.9        1.7        0.4        1.        ]
 [5.4        3.7        1.5        0.2        1.        ]
 [5.8        4.         1.2        0.2        1.        ]
 [5.7        4.4        1.5        0.4        1.        ]
 [5.4        3.9        1.3        0.4        1.        ]
 [5.1        3.5        1.4        0.3        1.        ]
 [5.7        3.8        1.7        0.3        1.        ]
 [5.1        3.8        1.5        0.3        1.        ]
 [5.4        3.4        1.7        0.2        1.        ]
 [5.1        3.7        1.5        0.4        1.        ]
 [5.1        3.3        1.7        0.5        1.        ]
 [5.2        3.5        1.5        0.2        1.        ]
 [5.2        3.4        1.4        0.2        1.        ]
 [5.4        3.4        1.5        0.4        1.        ]
 [5.2        4.1        1.5        0.1        1.        ]
 [5.5        4.